// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAblswkcDV6-AOsv5rn6F7t6ns7y5FF3kg',
    appId: '1:116399526887:web:75a054c2960533321a6342',
    messagingSenderId: '116399526887',
    projectId: 'khota-988e6',
    authDomain: 'khota-988e6.firebaseapp.com',
    storageBucket: 'khota-988e6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAL0hb2NNPgMGZ_uksl4qde7GxR1vH-DGA',
    appId: '1:116399526887:android:e146b608941ff3081a6342',
    messagingSenderId: '116399526887',
    projectId: 'khota-988e6',
    storageBucket: 'khota-988e6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYm85KlUwHKrbtcfr6HYeTYCOjiytKVzE',
    appId: '1:116399526887:ios:f60e5143a17a3f161a6342',
    messagingSenderId: '116399526887',
    projectId: 'khota-988e6',
    storageBucket: 'khota-988e6.firebasestorage.app',
    iosBundleId: 'sa.edu.ksu.khotaApp',
  );
}
